spring.application.name=cupcake-store

# Usa a variável de ambiente DB_URL se existir, senão usa o localhost
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cupcake_store}
spring.datasource.driverClassName=org.postgresql.Driver

# Usa a variável DB_USERNAME se existir, senão usa "cupcake_user"
spring.datasource.username=${DB_USERNAME:cupcake_user}

# Usa a variável DB_PASSWORD se existir, senão usa "123456"
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect