@startuml Cliente

start

:Visualizar cupcakes disponíveis;
:Selecionar cupcake;
:Solicitar adição ao carrinho;

if (Usuário está logado?) then (Sim)

    :Adicionar cupcake ao carrinho;

else (Não)

    if (Usuário possui conta?) then (Sim)
        :Realizar login;
        :Autenticação validada;
    else (Não)
        :Realizar cadastro;
        :Conta criada;
        :Realizar login;
    endif

    :Adicionar cupcake ao carrinho;

endif

:Solicitar finalização do pedido;
:Confirmar pedido;

:Processar pedido;
:Registrar pedido no sistema;

stop

@enduml

@startuml Admin

start

:Realizar Login;

if (Login válido?) then (Sim)

    :Escolher Ação;

    if (Qual ação?) then (Cadastrar)
        :Preencher Dados;
        :Salvar no Banco;

    elseif (Editar)
        :Selecionar Cupcake;
        :Atualizar Dados;
        :Salvar no Banco;

    elseif (Remover)
        :Selecionar Cupcake;
        :Remover do Banco;

    elseif (Atualizar Estoque)
        :Selecionar Cupcake;
        :Alterar Quantidade;
        :Salvar no Banco;

    elseif (Visualizar Pedidos)
        :Buscar Pedidos no Banco;
    endif

else (Não)
    :Exibir Erro de Login;
endif

stop

@enduml